import type { Food } from '../services/foods'

export const DEFAULT_FOODS: Partial<Food>[] = [
  { name: 'Arroz branco', calories: 130, protein: 2.7, carbs: 28.2, fat: 0.3, is_default: true },
  { name: 'Feijão carioca', calories: 76, protein: 4.8, carbs: 13.6, fat: 0.5, is_default: true },
  { name: 'Frango grelhado', calories: 165, protein: 31, carbs: 0, fat: 3.6, is_default: true },
  { name: 'Peito de frango', calories: 165, protein: 31, carbs: 0, fat: 3.6, is_default: true },
  { name: 'Carne bovina (patinho)', calories: 134, protein: 24, carbs: 0, fat: 3.5, is_default: true },
  { name: 'Carne moída', calories: 212, protein: 18.6, carbs: 0, fat: 15.1, is_default: true },
  { name: 'Ovo inteiro', calories: 155, protein: 12.6, carbs: 1.1, fat: 10.6, is_default: true },
  { name: 'Clara de ovo', calories: 52, protein: 10.9, carbs: 0.7, fat: 0.2, is_default: true },
  { name: 'Leite integral', calories: 61, protein: 3.2, carbs: 4.8, fat: 3.3, is_default: true },
  { name: 'Leite desnatado', calories: 34, protein: 3.4, carbs: 5, fat: 0.1, is_default: true },
  { name: 'Queijo minas', calories: 264, protein: 17.4, carbs: 3.1, fat: 20.4, is_default: true },
  { name: 'Queijo cottage', calories: 98, protein: 11.7, carbs: 3.4, fat: 4.3, is_default: true },
  { name: 'Banana', calories: 89, protein: 1.1, carbs: 22.8, fat: 0.3, is_default: true },
  { name: 'Maçã', calories: 52, protein: 0.3, carbs: 13.8, fat: 0.2, is_default: true },
  { name: 'Laranja', calories: 47, protein: 0.9, carbs: 11.8, fat: 0.1, is_default: true },
  { name: 'Abacate', calories: 160, protein: 2, carbs: 8.5, fat: 14.7, is_default: true },
  { name: 'Batata inglesa', calories: 77, protein: 2, carbs: 17, fat: 0.1, is_default: true },
  { name: 'Batata doce', calories: 86, protein: 1.6, carbs: 20.1, fat: 0.1, is_default: true },
  { name: 'Mandioca', calories: 125, protein: 1.2, carbs: 30.1, fat: 0.2, is_default: true },
  { name: 'Pão francês', calories: 300, protein: 8.5, carbs: 57, fat: 3.5, is_default: true },
  { name: 'Pão integral', calories: 247, protein: 13, carbs: 41, fat: 3.4, is_default: true },
  { name: 'Aveia', calories: 389, protein: 16.9, carbs: 66.3, fat: 6.9, is_default: true },
  { name: 'Macarrão cozido', calories: 157, protein: 5.8, carbs: 31, fat: 0.9, is_default: true },
  { name: 'Brócolis', calories: 34, protein: 2.8, carbs: 7, fat: 0.4, is_default: true },
  { name: 'Cenoura', calories: 41, protein: 0.9, carbs: 9.6, fat: 0.2, is_default: true },
  { name: 'Tomate', calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2, is_default: true },
  { name: 'Alface', calories: 15, protein: 1.4, carbs: 2.9, fat: 0.2, is_default: true },
  { name: 'Pepino', calories: 16, protein: 0.7, carbs: 3.6, fat: 0.1, is_default: true },
  { name: 'Mandioca frita', calories: 331, protein: 1.5, carbs: 79, fat: 1.3, is_default: true },
  { name: 'Batata frita', calories: 312, protein: 3.4, carbs: 41, fat: 15, is_default: true },
  { name: 'Peixe tilápia', calories: 96, protein: 20.1, carbs: 0, fat: 1.7, is_default: true },
  { name: 'Sardinha', calories: 208, protein: 24.6, carbs: 0, fat: 11.4, is_default: true },
  { name: 'Atum (conserva)', calories: 128, protein: 29, carbs: 0, fat: 0.6, is_default: true },
  { name: 'Café sem açúcar', calories: 2, protein: 0.3, carbs: 0, fat: 0, is_default: true },
  { name: 'Suc de laranja', calories: 45, protein: 0.7, carbs: 10.4, fat: 0.2, is_default: true },
  { name: 'Requeijão', calories: 302, protein: 7.2, carbs: 4.1, fat: 28.8, is_default: true },
  { name: 'Manteiga', calories: 717, protein: 0.9, carbs: 0.1, fat: 81, is_default: true },
  { name: 'Azeite de oliva', calories: 884, protein: 0, carbs: 0, fat: 100, is_default: true },
  { name: 'Mel', calories: 304, protein: 0.3, carbs: 82.4, fat: 0, is_default: true },
  { name: 'Whey protein', calories: 120, protein: 24, carbs: 3, fat: 1.5, is_default: true },
]
